### ISSUE TITLE
Events cannot be parsed

### ISSUE THREAD

**Issue by mikkoto** [adzerk/adzerk-android-sdk#51]
We've been using your Native Ads API successfully for a while now. However, now that we're about to add custom event reporting we noticed that your API seems to give different results than what is specified in your [Response API description](http://help.adzerk.com/hc/en-us/articles/203193935-Response):

- according to spec we should receive events in format `{ eventId: 12, eventUrl: "http://engine.adzerk.net/e.gif?..." }` 
- instead we're receiving them in format `{ id: 12, url: "http://engine.adzerk.net/e.gif?..." }`

As such, the android SDK cannot be used for getting event ids and urls.

**Comment by karnowski** [comment]
You're totally correct on the incorrect documentation!  Thanks for that!

I've updated the response documentation, and we are reviewing your pull request now.

**Comment by daveyarwood** [comment]
This change is included in [0.2.0](https://bintray.com/adzerk/Maven/com.adzerk.android.sdk/0.2.0), available now.

Thanks for the PR!
