### ISSUE TITLE
Use Adzerk "e-dash" domains

### ISSUE THREAD

**Issue by karnowski** [adzerk/adzerk-android-sdk#68]
## Background
For operational, performance, and data privacy concerns, Adzerk has migrated customers from the old default Decision and UserDB APIs hostname, `engine.adzerk.net`, onto individual URLs based on their network ID.

The new "e-dash" style URLs look like:  
`e-[networkid].adzerk.net`

For example, the demo network, `23`, use the URL:
`e-23.adzerk.net`

## Acceptance Criteria

- The SDK no longer uses the `engine.adzerk.net` default.
- The default URL's hostname is now based on a top-level network ID passed in during initialization.
- The default hostname follows the "e-dash" pattern: `e-[networkid].adzerk.net`
- An integrating developer can explicitly override the hostname.  In this case the "e-dash" hostname is ignored.

## Tech Notes

Note that you can still set a network ID on the individual placements, although in practice no one really does this.  If they do, however, then the top-level request still needs to go to one and only one "e-dash" domain host.  So we'll need to add a top-level network ID that determines the host.  The new Decision SDKs (Java, JavaScript, Ruby, Python) also use that top-level on the placement level if it's not explicitly set.  It'd be nice to follow that approach here as well, but it is not strictly required.

I didn't see a top-level `networkId` parameter, so we'll likely need to make a breaking change that requires one.  Perhaps on the `getInstance` method?  It's okay to make a breaking change in this case.  We'll just need to document the change.

**Comment by karnowski** [comment]
Also, I'm assuming that no cookies or other "local storage" will be disrupted by this URL change, right?

**Comment by bdiegel** [comment]
> I didn't see a top-level networkId parameter, so we'll likely need to make a breaking change that requires one. Perhaps on the getInstance method? It's okay to make a breaking change in this case. We'll just need to document the change.

Recommend we move away from Singleton pattern and use a Builder then. It will provide more flexibility in the future if we want to add additional configuration.  Something like:

` AdzerkSdk sdk = new AdzerkSdk.Builder().networkId(23).hostname("myhostname").build();`
