### ISSUE TITLE
Stop sending the `time` param on all requests

### ISSUE THREAD

**Issue by karnowski** [adzerk/adzerk-android-sdk#77]
## Background

The `time` parameter is actually a debugging and testing tool that is no longer a documented feature of Adzerk.  It may be phased out at any time.  However, both the Android & iOS SDKs are sending it on all requests.  Unless there's a really good reason to send it (is there?) then we should remove this unnecessary and potentially error-inducing parameter.

## Acceptance Criteria

- The `time` param is no longer sent on Android SDK requests.

**Comment by bdiegel** [comment]
https://github.com/adzerk/adzerk-android-sdk/blob/2d85eddc9e19fe8e937bd0f738d9b3aa26a8d73f/sdk/src/main/java/com/adzerk/android/sdk/rest/Request.java#L55
