### ISSUE TITLE
Support Android 5.0 (API 21) as minSDK

### ISSUE THREAD

**Issue by haart28** [adzerk/adzerk-android-sdk#88]
Hello @bdiegel, could you please explain why the project minSdk is 22 (Android 5.1) instead of 21?
I found the commit when minSdk was changed from Android 8.0 to Android 5.1, but I didn't find the reason.
https://github.com/adzerk/adzerk-android-sdk/commit/63881ef338b63a4f6287bd3389e99f350d7a8235

**Comment by karnowski** [comment]
@haart28 We're targeting a Java v1.8 or higher, and minSdk 22 works on v1.8 when we include the desugaring options.  Anything farther back, however, requires Java v1.7 which changes several of our dependencies.

I'd love to hear more about your use case, though.  Why is API 21 important to you?  Please contact me at `lkarnowski AT adzerk.com`.
